next/backend/meili/commonSearchFetcher.ts
next/components/AppLayout/Header.tsx
next/components/AppLayout/Navigation/HeaderNavigation.tsx
next/components/AppLayout/Navigation/NavigationItem.tsx
next/components/pages/SearchPage.tsx
next/components/pages/sidebarContentPage.tsx
next/pages/index.tsx
next/public/locales/en/common.json
next/public/locales/sk/common.json
strapi/config/plugins.js

- add Documents
- remove Premises - they have their own subpages
- minor visual fixes

MKB-481: fixes after search

---

next/components/AppLayout/Navigation/Subnavigation.tsx
next/components/HomePage/Promos/PromoEventCard.tsx
next/components/HomePage/Promos/PromoNewsCard.tsx
next/components/HomePage/SectionFaq.tsx
next/components/HomePage/SectionLibraryNews.tsx
next/components/HomePage/SectionLocalities.tsx
next/components/Molecules/FieldWrapper.tsx
next/components/Molecules/LocalityDetails.tsx
next/components/forms/FormFooter.tsx
next/components/pages/SearchPage.tsx
next/components/pages/eventsListingPage.tsx
next/components/styleguide/Stack.tsx
next/components/styleguide/Wrapper.tsx
next/components/ui/Chip/Chip.tsx
next/components/ui/Documents/Documents.tsx
next/components/ui/ExternalLinks/ExternalLinks.tsx
next/components/ui/Localities/Localities.tsx
next/components/ui/LocalityMap/LocalityMap.tsx
next/components/ui/Subpages/Subpages.tsx
next/styles/globals.css
next/tailwind.config.js

- fix heading font sizes - there was a mistake in figma that I used during refactorin (forgotten old font sizes written by numbers, not matching final design)
- run autofix eslint - mostly classes order

MKB-601: fix font sizes

---

next/components/AppLayout/Navigation/Subnavigation.tsx
next/components/HomePage/Promos/PromoEventCard.tsx
next/components/HomePage/Promos/PromoNewsCard.tsx
next/components/HomePage/SectionFaq.tsx
next/components/HomePage/SectionLibraryNews.tsx
next/components/HomePage/SectionLocalities.tsx
next/components/Molecules/FieldWrapper.tsx
next/components/Molecules/LocalityDetails.tsx
next/components/forms/FormFooter.tsx
next/components/pages/SearchPage.tsx
next/components/pages/eventsListingPage.tsx
next/components/styleguide/Stack.tsx
next/components/styleguide/Wrapper.tsx
next/components/ui/Chip/Chip.tsx
next/components/ui/Documents/Documents.tsx
next/components/ui/ExternalLinks/ExternalLinks.tsx
next/components/ui/Localities/Localities.tsx
next/components/ui/LocalityMap/LocalityMap.tsx
next/components/ui/Subpages/Subpages.tsx
next/styles/globals.css
next/tailwind.config.js

This reverts commit e3e04364f24bf7a511ee1176bd56975aa8874854.

Revert "Revert "MKB-601: fix font sizes (#70)""

---

next/components/Atoms/TagsDisplay.tsx
next/components/HomePage/Promos/PromoEventCard.tsx
next/components/HomePage/Promos/PromoNewsCard.tsx
next/components/HomePage/SectionPromos.tsx

- it's not perfect, it should be calculated, not hardcoded, but it works better than before and we need to quick fix it now

MKB-660: update promo section height and layout

---

next/backend/meili/fetchers/commonSearchFetcher.ts
next/components/HomePage/Promos/PromoNewsCard.tsx
next/components/HomePage/SectionHomepageNewBooks.tsx
next/components/pages/SearchPage.tsx
next/public/locales/en/common.json
next/public/locales/sk/common.json
strapi/config/plugins.js

Fixes search notice

---

next/components/forms/SpaceReservationForm/index.tsx

Added google calendar into Space Reservation form (prototype for monday presentation)
- separate calendars for each room
- switching proper calendars after room select

MKB-570 - Introduced google calendar to form

---

next/components/pages/NoticePage.tsx
next/graphql/index.ts
next/graphql/queries/Notices.graphql
strapi/schema.graphql
strapi/src/api/notice/content-types/notice/schema.json

MKB-664: change files to basic documents in Notice

---

next/components/HomePage/Carousel.tsx
next/components/HomePage/Promos/PromoEventCard.tsx
next/components/HomePage/SectionHomepageNewBooks.tsx
next/components/HomePage/SectionLibraryNews.tsx
next/components/HomePage/SectionPromos.tsx
next/components/HomePage/VerticalCardButton.tsx
next/components/Molecules/Carousel/Carousel.tsx
next/components/Molecules/Carousel/SliderControl/SliderControl.tsx
next/modules/common/Button.tsx
next/tailwind.config.js

Create generic Carousel component and use it in:
- SectionPromo
- SectionLibraryNews

MKB-671 create generic component Carousel

---

next/package.json
next/services/graphql/index.ts

For better readability index file is formater right after it is generated.

formating generated index file

---

strapi/kubernetes/base/.env
strapi/kubernetes/envs/Dev/.env
strapi/kubernetes/envs/Prod/.env
strapi/kubernetes/envs/Staging/.env

Reverts bratislava/mestskakniznica.sk#175

Revert "Fix ports"

---

next/services/graphql/index.ts
strapi/schema.graphql
strapi/src/api/basic-document/content-types/basic-document/schema.json
strapi/src/api/disclosure/content-types/disclosure/schema.json
strapi/src/api/disclosure/controllers/disclosure.js
strapi/src/api/disclosure/routes/disclosure.js
strapi/src/api/disclosure/services/disclosure.js
strapi/src/api/document-category/content-types/document-category/schema.json
strapi/src/api/document-category/controllers/document-category.js
strapi/src/api/document-category/routes/document-category.js
strapi/src/api/document-category/services/document-category.js
strapi/src/api/document/content-types/document/schema.json
strapi/src/api/document/controllers/document.js
strapi/src/api/document/routes/document.js
strapi/src/api/document/services/document.js
strapi/src/api/file-category/content-types/file-category/schema.json

TODO custom validations will be added after data migration

MKB-714: Create new content types for documents and disclosures

---

next/package.json
next/services/opac/newBooksService.ts
next/yarn.lock

The library is broken and doesn't work all the time, therefore the check doesn't work on production env.

Fix url filesize

---

next/components/Molecules/EventDetails.tsx
next/components/Molecules/NoticeCard.tsx
next/components/Molecules/Sections.tsx
next/components/pages/NoticePage.tsx
next/components/ui/Documents/Documents.tsx
next/services/graphql/index.ts
next/services/graphql/queries/queries.graphql
strapi/schema.graphql
strapi/src/api/notice/content-types/notice/schema.json
strapi/src/components/sections/documents.json

+ change listingImage in Notices to single media

MKB-710: add disclosures to Documents section

---

next/components/AppLayout/Navigation/HeaderSearchBox.tsx
next/hooks/useSearch.ts
next/modules/sections/BlogPostsListingSection.tsx
next/modules/sections/DocumentsListingSection.tsx
next/modules/sections/EventsListingSection.tsx
next/modules/sections/NewBooksSection.tsx
next/modules/sections/NoticesListingSection.tsx
next/utils/useRoutePreservedState.ts

MKB-559 Route preserved state

---

next/components/forms/CityLibraryRegistrationForm/index.tsx
next/components/pages/DocumentPage.tsx
next/pages/api/register.ts

MKB775 - fixed birthday datetime formatting using different TZ (moved logic from BE to FE)
MKB777 - updated document download CTA wording

Mkb 776/fix birthday tz

---

next/components/pages/SearchPage.tsx
next/package.json
next/pages/_app.tsx
next/yarn.lock

Added search logging to plausible via custom events.
Replaced hardcoded plausible js file and added next-plausible package

MKB-779 - Added plausible custom event (search)

---

next/components/forms/BookList/BookListNotInLibrary.tsx
next/components/forms/BookNotInLibraryForm/index.tsx
next/components/forms/CityLibraryRegistrationForm/index.tsx
next/components/forms/RechercheReservationForm/index.tsx
next/public/locales/en/forms.json
next/public/locales/sk/forms.json

- added/updated translation
- removed required fields for few inputs
- added book list for "not in library" form

MKB-871 - Updated translations, added booklist to form

---

next/components/forms/BookNotInLibraryForm/index.tsx
next/components/forms/ServiceReservationForm/index.tsx
next/public/locales/en/forms.json
next/public/locales/sk/forms.json

MKB-782 - Updated forms

---

next/components/ui/NewsLetter/NewsLetter.tsx
next/tailwind.config.js

Task details here [MKB-785](https://inovaciebratislava.atlassian.net/browse/MKB-785) 
(branch named MKB-516 wrongly)
[MKB-785]: https://inovaciebratislava.atlassian.net/browse/MKB-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MKB-785 - Newsletter submit fixed button

---

next/components/pages/SearchPage.tsx

-  https://github.com/bratislava/mestskakniznica.sk/issues/285

Replace search dummy data with skeleton

---

next/pages/index.tsx
next/services/graphql/index.ts
next/services/graphql/queries/Homepage.gql
strapi/schema.graphql
strapi/src/api/home-page/content-types/home-page/schema.json
strapi/src/components/homepage/promoted-content.json

Added ability to add promoted content (events, notices) directly to homepage single page

MKB-698 - Added promoted content to homepage

---

next/components/forms/CityLibraryRegistrationForm/options.ts

- Make content-related adjustments to the form
- SVOP category for the newly added item was taken from: https://opac.mestskakniznica.sk/opac?fn=*registerNewUser&nusr=_sem_pojde_odkaz_na_json and accessed via DevTools
- Open the path `/sluzby/citanie/ako-sa-prihlasit-do-kniznice`
- The prices for high school students and corporations are adjusted as specified
- A new item "My Library Club" is present

#347 Adjust the content of the Registration form

---

next/services/graphql/index.ts
strapi/schema.graphql
strapi/src/api/blog-post/content-types/blog-post/schema.json

Add new field to Blog posts in Strapi, as preparation for FE part of this task.

#344 Add `isCurrentChangeInOpeningHours` flag to BlogPosts in Strapi

---

strapi/config/database.js
strapi/database/migrations/2023.06.14T00.00.00.update-file-paths.js
strapi/package.json
strapi/src/plugins/navikronos/package.json
strapi/src/plugins/navikronos/yarn.lock
strapi/yarn.lock

- Navikronos plugin for Strapi failed at build, apparently resolved with last commit

#362 Upgrade Strapi to 4.11.4

---

next/components/forms/GiftCardReservationForm/options.ts

- Update the prices and add new user category (My library programme)
| Before | After |
|----------|----------|
| <img width="686" alt="Screenshot 2025-01-30 at 14 36 20" src="https://github.com/user-attachments/assets/304e7927-4ff8-462f-9f72-83fa00836a28" /> | <img width="868" alt="Screenshot 2025-01-30 at 14 24 49" src="https://github.com/user-attachments/assets/d7f4b7d3-aa3a-43ef-bf80-320b7ed3e99f" /> |
- Visit https://mestskakniznica.sk/sluzby/nastroje/darcekova-poukazka
- Confirm whether the changes correspond to the requested changes

#363 Update Gift certificate form

---

next/kubernetes/envs/Dev/kustomization.yml
next/kubernetes/envs/Dev/scaler.yml
next/kubernetes/envs/Prod/kustomization.yml
next/kubernetes/envs/Prod/scaler.yml
next/kubernetes/envs/Staging/kustomization.yml
next/kubernetes/envs/Staging/scaler.yml
strapi/kubernetes/envs/Dev/config.json
strapi/kubernetes/envs/Dev/kustomization.yml
strapi/kubernetes/envs/Dev/scaler.yml
strapi/kubernetes/envs/Prod/config.json
strapi/kubernetes/envs/Prod/kustomization.yml
strapi/kubernetes/envs/Prod/scaler.yml
strapi/kubernetes/envs/Staging/config.json
strapi/kubernetes/envs/Staging/kustomization.yml
strapi/kubernetes/envs/Staging/scaler.yml

* Added KEDA Prometheus scalers for Dev environment that scale down idle deployments after 6h of no incoming requests
* Added KEDA Prometheus scalers for Stage environment that scale down idle deployments after 7d of no incoming requests
* Added KEDA Prometheus scalers for Prod environment that scale up frontend app if resources utilization is >= 85% for more then 10 minutes. Scales up to 5 instances

feat: added KEDA (HPA) Prometheus scalers

---

next/modules/sections/EventsListingSection.tsx
next/package.json

Add lincese field into `next/package.json` as in other projects.
Note: one file somehow didn't get lint fixed in previewous PRs 🤷 so I commited it here.

#326 Add EUPL-1.2 license

---

next/modules/breadcrumbs/BreadcrumbItem.tsx

See issue description and code comment.
Breadcrumbs should work.

#405 Fix Breadcrumb links

---

next/Dockerfile
next/package.json
next/yarn.lock

Note:
- downgrade graphql-request to make it compatible

#459 Update Next to 14.2.26

---

next/components/ui/Input/Input.tsx
next/components/ui/Select/Select.tsx

#468 Fix focus rings for select and input

---

next/kubernetes/base/deployment.yml
next/kubernetes/envs/Dev/kustomization.yml
next/kubernetes/envs/Dev/secrets/cloudflare-turnstile.secret.yml
next/kubernetes/envs/Prod/kustomization.yml
next/kubernetes/envs/Prod/secrets/cloudflare-turnstile.secret.yml
next/kubernetes/envs/Prod/secrets/general.mono.secret.yml
next/kubernetes/envs/Staging/kustomization.yml
next/kubernetes/envs/Staging/secrets/cloudflare-turnstile.secret.yml
next/kubernetes/envs/Staging/secrets/general.mono.secret.yml
strapi/kubernetes/base/deployment.yml
strapi/kubernetes/envs/Dev/kustomization.yml
strapi/kubernetes/envs/Dev/secrets/revalidate.secret.yml
strapi/kubernetes/envs/Prod/kustomization.yml
strapi/kubernetes/envs/Prod/secrets/revalidate.secret.yml
strapi/kubernetes/envs/Staging/kustomization.yml
strapi/kubernetes/envs/Staging/secrets/revalidate.secret.yml

* Moved secrets from `kubernetes/base` that were environment specific into respective `envs/` folders
* Added project labels into secrets
* Added revalidate secret

Secret cleanup & added Strapi revalidate secret

---

next/pages/api/revalidate.ts

Adding logs for revalidate api, needed for better testing

Add logs for revalidate
